version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: "."
        target: /app
    command: ["mix", "phx.server"]
    working_dir: /app
    stdin_open: true
    tty: true
